# ------------------------------------------------------------------------------
# The deployment file considers master node also for targetting deployments
# The following command needs to be set into both master node and worker nodes
# kubectl label node k8s-master kubernetes.io/system-apis=allow
# ------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-locator-app-v001
spec:
  selector:
      matchLabels:
        app: country-locator-app-v001
  replicas: 1
  template:
    metadata:
      labels:
        app: country-locator-app-v001
    spec:
      nodeSelector:
        region: primary
      #nodeSelector:
      #  kubernetes.io/system-apis: allow
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #    - labelSelector:
      #        matchExpressions:
      #        - key: app
      #          operator: In
      #          values:
      #          - country-locator-app-v001
      #      topologyKey: "kubernetes.io/hostname"
      # ----------------------------------
      # will target master node deployment
      #tolerations:
      #  - key: "node-role.kubernetes.io/master"
      #    operator: "Exists"
      #    effect: "NoSchedule"
      # ----------------------------------
      containers:
        - name: country-locator-app-v001
          image: srivatsabc/country-locator-app:os-s-api-v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 7900
          env:
            - name: RUNTIME_ENV_TYPE #In order to help mule application pickup the right jdbc properties
              valueFrom:
                configMapKeyRef:
                  name: country-locator-app-v001-config
                  key: RUNTIME_ENV_TYPE
